# 旧版GCN模型

dataset:
  name: Minesweeper

model:
  layers:
  - type: dropout
    dropout_rate: 0.4
  - type: gcn
    hidden_dim: 128
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.4
  - type: gcn
    hidden_dim: 128
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 128
training:
  optimizer: 'adam'
  lr: 0.014125801627629555
  wd: 3.510434800660086e-05
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
