# 旧版GCN模型

dataset:
  name: Roman-empire

model:
  layers:
  - type: dropout
    dropout_rate: 0.5
  - type: gcn
    hidden_dim: 512
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.5
  - type: gcn
    hidden_dim: 512
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 512
training:
  optimizer: 'adam'
  lr: 0.05217393836579938
  wd: 7.419865431466125e-05
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
