# 旧版GCN模型

dataset:
  name: CS

model:
  layers:
  - type: dropout
    dropout_rate: 0.2
  - type: gcn
    hidden_dim: 64
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.2
  - type: gcn
    hidden_dim: 64
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 64
training:
  optimizer: 'adam'
  lr: 0.00589532345231382
  wd: 0.006422524367860309
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
