# 旧版GCN模型

dataset:
  name: CoraFull

model:
  layers:
  - type: dropout
    dropout_rate: 0.7
  - type: gcn
    hidden_dim: 512
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.7
  - type: gcn
    hidden_dim: 512
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 512
training:
  optimizer: 'adam'
  lr: 0.007132495319416772
  wd: 0.006678412787951576
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
