# 旧版GCN模型

dataset:
  name: CiteSeerFull

model:
  layers:
  - type: dropout
    dropout_rate: 0.25
  - type: gcn
    hidden_dim: 256
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.25
  - type: gcn
    hidden_dim: 256
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 256
training:
  optimizer: 'adam'
  lr: 0.016553508588282802
  wd: 0.0007795626344720707
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
