# GAT模型

dataset:
  name: Photo

model:
  # GAT通常使用ELU作为激活函数，效果比ReLU好
  activation: relu

  layers:
    # --- 第一层 (输入层 -> 隐藏层) ---
  - type: dropout
    dropout_rate: 0.1
  - type: gat
    hidden_dim: 64
    heads: 8
  - type: elu

  - type: dropout
    dropout_rate: 0.1
  - type: gat
    hidden_dim: 64
    heads: 8
  - type: elu

training:
  optimizer: 'adam'
  lr: 0.0010524467995134668 # GAT通常需要比GCN更小的学习率
  wd: 0.009801920729866352 # 权重衰减
  epochs: 1000
  seeds: [42, 100, 2023]
