# 旧版GCN模型

dataset:
  name: genius

model:
  layers:
  - type: dropout
    dropout_rate: 0.25
  - type: gcn
    hidden_dim: 64
  - type: layernorm
  - type: relu

  - type: dropout
    dropout_rate: 0.25
  - type: gcn
    hidden_dim: 64
  - type: layernorm
  - type: relu

  - type: gcn  # 输出层不会添加激活和dropout

    hidden_dim: 64
training:
  optimizer: 'adam'
  lr: 0.006021737107102856
  wd: 6.530544344471052e-05
  epochs: 1000
  seeds: [42, 100, 2023] # <-- 在这里设置默认种子
